version: 0.0
os: windows

hooks:
  AfterInstall:
    - location: scripts/Create-File.ps1
      runas: Administrator
      timeout: 300
      args:
        - "-Destination"
        - "C:\\hello\\file.txt"
        - "-Content"
        - "Automated by CodePipeline"
